extends:
  - "@commitlint/config-conventional"
rules:
  # disable line length limits on the message body so semantic-release can include links
  body-max-line-length:
    - 0
    - always
  footer-max-line-length:
    - 0
    - always
  # prevent commit if "type(scope?): subject" not in lowercase
  type-case:
    - 2
    - always
    - lower-case
  scope-case:
    - 2
    - always
    - lower-case
  subject-case:
    - 2
    - always
    - lower-case