name: Package and Release
on:
  workflow_run:
    workflows: 
      - Build and Test
    branches:
      - main
    types:
      - completed

env:
  nuget_feed_source: https://nuget.pkg.github.com/reapit/index.json
  project_path: ./src/Reapit.Platform.Common/Reapit.Platform.Common.csproj
  HUSKY: 0
jobs:
  package-and-release:
    name: package and release
    runs-on: ubuntu-latest
    if: ${{ false }}
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Get token for the release app
      - name: 🔐 generate release app token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 1082088 # todo: make this a secret
          private-key: ${{ secrets.PLATFORM_RELEASE_BOT_PRIVATE_KEY }}

      - name: 🪪 get release app user credentials
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: 👋 configure git user details
        run: |
          git config --global user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com>'

      # setup the environment
      - name: 📩 checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
          persist-credentials: false

      - name: ⚙️ setup node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: 🕸️ setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: 🔨 install dependencies
        run: npm ci --include=dev

      - name: ✨ create release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: npx semantic-release

      - name: 🎉 publish to packages
        if: ${{ false }}
        run: |
          dotnet nuget add source ${{ env.nuget_feed_source }} --name github --store-password-in-clear-text --username reapit --password ${{ secrets.GH_NUGET_WRITE_TOKEN }}
          dotnet pack ${{ env.project_path }} -o ./package/ -c Release
          dotnet nuget push ./package/*.nupkg --source ${{ env.nuget_feed_source }} --api-key ${{ secrets.GH_NUGET_WRITE_TOKEN }} --skip-duplicate --no-symbols